'use server';

/**
 * @fileOverview An AI agent that expands user-written text using Google Gemini 2.5 Flash.
 *
 * - expandTextWithAI - A function that handles the text expansion process.
 * - ExpandTextWithAIInput - The input type for the expandTextWithAI function.
 * - ExpandTextWithAIOutput - The return type for the expandTextWithAI function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExpandTextWithAIInputSchema = z.object({
  text: z.string().describe('The text to expand.'),
});
export type ExpandTextWithAIInput = z.infer<typeof ExpandTextWithAIInputSchema>;

const ExpandTextWithAIOutputSchema = z.object({
  expandedText: z.string().describe('The expanded text generated by the AI.'),
});
export type ExpandTextWithAIOutput = z.infer<typeof ExpandTextWithAIOutputSchema>;

export async function expandTextWithAI(input: ExpandTextWithAIInput): Promise<ExpandTextWithAIOutput> {
  return expandTextWithAIFlow(input);
}

const expandTextWithAIPrompt = ai.definePrompt({
  name: 'expandTextWithAIPrompt',
  input: {schema: ExpandTextWithAIInputSchema},
  output: {schema: ExpandTextWithAIOutputSchema},
  prompt: `You are an AI writing assistant. Expand the following text based on its context:\n\n{{{text}}}`,
});

const expandTextWithAIFlow = ai.defineFlow(
  {
    name: 'expandTextWithAIFlow',
    inputSchema: ExpandTextWithAIInputSchema,
    outputSchema: ExpandTextWithAIOutputSchema,
  },
  async input => {
    const {output} = await expandTextWithAIPrompt(input);
    return output!;
  }
);
