'use server';

/**
 * @fileOverview An AI agent that expands user-written text using Google Gemini 2.5 Flash.
 *
 * - expandTextWithAI - A function that handles the text expansion process.
 * - ExpandTextWithAIInput - The input type for the expandTextWithAI function.
 * - ExpandTextWithAIOutput - The return type for the expandTextWithAI function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const ExpandTextWithAIInputSchema = z.object({
  text: z.string().describe('The text to expand.'),
});
export type ExpandTextWithAIInput = z.infer<typeof ExpandTextWithAIInputSchema>;

const ExpandTextWithAIOutputSchema = z.object({
  expandedText: z.string().describe('The expanded text generated by the AI.'),
});
export type ExpandTextWithAIOutput = z.infer<typeof ExpandTextWithAIOutputSchema>;

export async function expandTextWithAI(input: ExpandTextWithAIInput): Promise<ExpandTextWithAIOutput> {
  return expandTextWithAIFlow(input);
}

const expandTextWithAIPrompt = ai.definePrompt({
  name: 'expandTextWithAIPrompt',
  input: {schema: ExpandTextWithAIInputSchema},
  output: {schema: ExpandTextWithAIOutputSchema},
  prompt: `You are an AI writing assistant. Your task is to continue the text provided by the user.
Do not repeat the user's text in your response. Only generate the next part of the text, adding to it naturally.
Ensure you add punctuation like commas and full stops where appropriate to make the text flow.

User's text:
"{{{text}}}"

Your direct continuation, starting from the character immediately after the user's last word:`,
});

const expandTextWithAIFlow = ai.defineFlow(
  {
    name: 'expandTextWithAIFlow',
    inputSchema: ExpandTextWithAIInputSchema,
    outputSchema: ExpandTextWithAIOutputSchema,
  },
  async input => {
    const {output} = await expandTextWithAIPrompt(input);
    return output!;
  }
);
